server:
  port: 9090
devservice:
  keycloak:
    jwkUrl: ${KEY_CLOAK_JWK_URL}
  gatewayservice:
    baseUrl: ${GATEWAY_BASE_URL}
    username: ${GATEWAY_ADMIN_USER}
    password: ${GATEWAY_ADMIN_PASSWORD}
  clientregistry:
    url: ${CLIENT_REGISTRY_URL:http://localhost:8080}
  email:
    clientName: ${EMAIL_CLIENT_NAME}
    sender: ${EMAIL_SENDER}
    receiver: ${EMAIL_RECEIVER}
    subject: ${EMAIL_SUBJECT}
    allowedOrigin: ${ALLOWED_ORIGIN_HOST:*}
    autoResponseBodyPath: ${AUTO_RESPONSE_BODY_PATH}
    autoResponseSubject: ${AUTO_RESPONSE_SUBJECT}
    autoResponseEnabled: ${AUTO_RESPONSE_ENABLED:false}
  googleservice:
    credentialPath: ${GOOGLE_SERVICE_CREDENTIAL_PATH}
    sheetId: ${GOOGLE_SERVICE_SHEET_ID}
    enabled: ${GOOGLE_SERVICE_ENABLED:false}
  support-requests:
    spreadsheetId: ${SUPPORT_REQUESTS_SPREADSHEET_ID}
    credentialPath: ${GOOGLE_SERVICE_CREDENTIAL_PATH}
  db:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT:5432}
    schema: ${DEV_SERVICE_DB_NAME}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    poolSize: ${MASTER_POOL_SIZE:5}
spring:
  mail:
    host: ${SMTP_HOST:smtp.mailtrap.io}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USER:b9d018e7253caf}
    password: ${SMTP_USER_PASSWORD:0b2e32cda91ecd}
    properties:
      main:
        lazy-initialization: true
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
  liquibase:
    change-log: classpath:liquibase:xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_service
    username: postgres
    password: password
logging:
  level:
    liquibase: INFO