server:
  port: 9090
devservice:
  keycloak:
    jwkUrl: http://localhost:9001/auth/realms/central-registry/protocol/openid-connect/certs
  gatewayservice:
    baseUrl: http://localhost:8000
    username: admin-user
    password: welcome
  clientregistry:
    url: http://localhost:8080
  email:
    clientName: Local Client
    sender: xyz@gmail.com
    receiver: xyz@gmail.com
    subject: Details
    autoResponseBodyPath: /Users/some_user/Documents/emailbody.txt
    autoResponseSubject: Thanks
    autoResponseEnabled: false
  googleservice:
    credentialPath: /PATH/TO/CREDENTIALS
    sheetId: 1CWgChfwZCTtQAdMGi1k7T5-dM8K2pKtp-odJ4p7RxlM
    enabled: false
spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: b9d018e7253caf
    password: 0b2e32cda91ecd
    properties:
      main:
        lazy-initialization: true
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
