server:
  port: 9090
devservice:
  keycloak:
    jwkUrl: ${KEY_CLOAK_JWK_URL}
  gatewayservice:
    baseUrl: ${GATEWAY_BASE_URL}
    username: ${GATEWAY_ADMIN_USER}
    password: ${GATEWAY_ADMIN_PASSWORD}
  clientregistry:
    url: ${CLIENT_REGISTRY_URL:http://localhost:8080}
  email:
    clientName: ${EMAIL_CLIENT_NAME}
    sender: ${EMAIL_SENDER}
    receiver: ${EMAIL_RECEIVER}
    subject: ${EMAIL_SUBJECT}
spring:
  mail:
    host: ${SMTP_HOST:smtp.mailtrap.io}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USER:b9d018e7253caf}
    password: ${SMTP_USER_PASSWORD:0b2e32cda91ecd}
    properties:
      main:
        lazy-initialization: true
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
