name: Build and push Docker Image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and unit tests
        run: ./gradlew clean build
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
      - name: Docker Registry
        env:
          DOCKER_REGISTRY_URL: docker.io
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      - name: Build docker image
        env:
          IMAGE_NAME: projecteka/dev-service
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $IMAGE_NAME:$RELEASE_VERSION -t $IMAGE_NAME:latest .
      - name: Push Docker Image to Registry
        env:
          IMAGE_NAME: projecteka/dev-service
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $IMAGE_NAME
